### ISSUE TITLE
Closing Pixel accounts

### ISSUE THREAD

**Issue by tygerxqt** [tygerxqt/tygr.dev#11]
# Moving to closed beta.
Due to a heavy amount of database errors occurring whenever I add a new feature or fix a bug, I'm going to move Pixel accounts back into closed beta. @NyanSpaghetti and @tygerxqt will be the only ones who have access to the database and profile and account page at this time. A blog post will also be made on this soon. 

**Tasks**
- [x] Check to see if users have admin permission, if so allow them through.
- [x] Disable Signup.
- [x] Invite admins.
- [x] ~~Remove login button from navbar.~~
- [x] Create blog post.

**Comment by tygerxqt** [comment]
Added the check to let admin pass through to profile and account page.

**Comment by tygerxqt** [comment]
Disabled signup.

**Comment by tygerxqt** [comment]
Successfully created admin accounts for @NyanSpaghetti and @tygerxqt.

**Comment by tygerxqt** [comment]
Created the blog post.

**Comment by tygerxqt** [comment]
Pushing changes to the `main` branch.
