### ISSUE TITLE
Pixel Accounts

### ISSUE THREAD

**Issue by tygerxqt** [tygerxqt/tygr.dev#12]
### Overview.
Pixels is a subscription service that starts at a minimum of $1 a month. Currently you can subscribe to Pixel at [Ko-Fi](https://ko-fi.com/tygerxqt) but it is very limiting on what I want to upload and share to subscribers. SO, I decided to make my own way to distribute  content, perks and rewards to subscribers. On top of that, I can use Pixel accounts to authenticate users in other personal applications. An example of this is my Discord bot [Cookie](https://github.com/tygerxqt/cookie), If you have your Discord account linked to your Pixel account, Cookie sees that and updates your roles depending if you are subscribed or not. I can use this in many different ways across different apps and projects. 

### Closed beta
This component used to be in open beta for the public but I have decided it would be better if we closed this until the end of development or on release. [Read more](https://github.com/tygerxqt/tygr.dev/issues/11).

### Tasks
- [x] https://github.com/tygerxqt/tygr.dev/pull/3 Add the ability to edit your profile.
- [x] https://github.com/tygerxqt/tygr.dev/pull/3 Add the ability to add and remove an avatar.
- [x]  https://github.com/tygerxqt/tygr.dev/pull/4 Add password update field.
- [x] https://github.com/tygerxqt/tygr.dev/pull/5 Allow users to link Identities like Discord and GitHub to unlock perks.
- [x] Add banners.
- [x] Add badges with permissions.
- [x] ~~Implement [Cookie](https://github.com/tygerxqt/cookie) to auto-assign Discord role.~~
- [x] ~~Implement [Cookie](https://github.com/tygerxqt/cookie) to auto-assign Git Permissions.~~
- [x] Tagging system to let users have the same username (`tygerxqt#0001`).
- [x] Create an account page to manage billing information. 
- [x] Setup Stripe for payment.

**Comment by tygerxqt** [comment]
Added a beta billing component: [`fc5f3d8` (#14)](https://github.com/tygerxqt/tygr.dev/pull/14/commits/fc5f3d87b59af32c45f11231ba435705476be3a3)
